#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# EC2 Bootstrap Script for Health & Wellness Screener
# Run this ONCE on a fresh Ubuntu 24.04 EC2 t2.micro instance.
#
# Usage:
#   chmod +x ec2-setup.sh
#   ./ec2-setup.sh
#
# Prerequisites:
#   - EC2 instance is running with Security Group ports 22, 80, 443 open
#   - You have SSH access as the 'ubuntu' user
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

echo "══════════════════════════════════════════════════════════"
echo "  HealthLens EC2 Setup — Starting"
echo "══════════════════════════════════════════════════════════"

# ── 1. System Updates ────────────────────────────────────────────────────────
echo "[1/7] Updating system packages..."
sudo apt update && sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y

# ── 2. Install Docker ────────────────────────────────────────────────────────
echo "[2/7] Installing Docker..."
sudo apt install -y docker.io docker-compose-v2
sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker ubuntu

# ── 3. Install Nginx & Certbot ──────────────────────────────────────────────
echo "[3/7] Installing Nginx and Certbot..."
sudo apt install -y nginx certbot python3-certbot-nginx

# ── 4. Clone Repository ─────────────────────────────────────────────────────
echo "[4/7] Cloning repository..."
APP_DIR="/home/ubuntu/health-screener"

if [ -d "$APP_DIR" ]; then
    echo "  Repository already exists. Pulling latest changes..."
    cd "$APP_DIR" && git pull origin main
else
    cd /home/ubuntu
    git clone https://github.com/Arnish-val/health-screener.git
    cd "$APP_DIR"
fi

# ── 5. Create Production Environment File ───────────────────────────────────
echo "[5/7] Creating production .env file..."
echo ""
echo "  ┌─────────────────────────────────────────────────────┐"
echo "  │  You will be prompted for configuration values.     │"
echo "  │  Press Enter to accept defaults shown in [brackets] │"
echo "  └─────────────────────────────────────────────────────┘"
echo ""

# Generate a random secret key
DEFAULT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")

read -p "  SECRET_KEY [$DEFAULT_SECRET]: " SECRET_KEY
SECRET_KEY=${SECRET_KEY:-$DEFAULT_SECRET}

read -p "  GOOGLE_CLIENT_ID []: " GOOGLE_CLIENT_ID
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-""}

read -p "  Vercel frontend URL (e.g., https://health-screener.vercel.app) []: " VERCEL_URL
VERCEL_URL=${VERCEL_URL:-""}

# Build CORS origins
if [ -n "$VERCEL_URL" ]; then
    CORS_ORIGINS="[\"${VERCEL_URL}\", \"http://localhost:5173\"]"
else
    CORS_ORIGINS="[\"http://localhost:5173\"]"
fi

cat > "$APP_DIR/backend/.env" << EOF
# ── Production Configuration ─────────────────────────────────
# Generated by ec2-setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Database: SQLite on local filesystem (zero cost)
DATABASE_URL=sqlite:///./health_screener.db

# Security
SECRET_KEY=${SECRET_KEY}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

# CORS — allow requests from the Vercel frontend
CORS_ORIGINS=${CORS_ORIGINS}

# App
DEBUG=false
EOF

echo "  ✓ .env file created at $APP_DIR/backend/.env"

# ── 6. Build and Run Docker Container ───────────────────────────────────────
echo "[6/7] Building Docker image (this may take 2-3 minutes)..."
cd "$APP_DIR"

# Build the Docker image
docker build -t health-screener-api -f backend/Dockerfile .

# Stop existing container if running
docker stop health-screener-api 2>/dev/null || true
docker rm health-screener-api 2>/dev/null || true

# Run the container
docker run -d \
    --name health-screener-api \
    --restart always \
    --env-file backend/.env \
    -v "$APP_DIR/ml_pipeline/models:/ml_pipeline/models:ro" \
    -p 8000:8000 \
    health-screener-api

echo "  ✓ Backend container is running on port 8000"

# ── 7. Configure Nginx Reverse Proxy ────────────────────────────────────────
echo "[7/7] Configuring Nginx..."

ELASTIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "YOUR_ELASTIC_IP")

sudo tee /etc/nginx/sites-available/health-screener > /dev/null << EOF
server {
    listen 80;
    server_name ${ELASTIC_IP} _;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    # Proxy to FastAPI backend
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Timeout settings for ML inference
        proxy_read_timeout 30s;
        proxy_connect_timeout 10s;
    }

    # Health check endpoint (for CI/CD verification)
    location /health {
        proxy_pass http://127.0.0.1:8000/health;
    }
}
EOF

sudo ln -sf /etc/nginx/sites-available/health-screener /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl restart nginx

echo ""
echo "══════════════════════════════════════════════════════════"
echo "  ✅ Setup Complete!"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "  API is live at:  http://${ELASTIC_IP}"
echo "  Swagger docs:    http://${ELASTIC_IP}/docs"
echo "  Health check:    http://${ELASTIC_IP}/health"
echo ""
echo "  ── Next Steps ──────────────────────────────────────────"
echo "  1. Set up free HTTPS with DuckDNS (see below)"
echo "  2. Update Vercel env var VITE_API_URL to your API URL"
echo "  3. Update Google OAuth authorized origins"
echo ""
echo "  ── Free HTTPS Setup (DuckDNS + Let's Encrypt) ─────────"
echo "  1. Go to https://www.duckdns.org and sign in with GitHub"
echo "  2. Create a subdomain (e.g., 'healthlens')"
echo "  3. Set the IP to: ${ELASTIC_IP}"
echo "  4. Run these commands:"
echo ""
echo "     # Update Nginx server_name"
echo "     sudo sed -i 's/server_name .*/server_name healthlens.duckdns.org;/' \\"
echo "       /etc/nginx/sites-available/health-screener"
echo "     sudo nginx -t && sudo systemctl restart nginx"
echo ""
echo "     # Get free SSL certificate"
echo "     sudo certbot --nginx -d healthlens.duckdns.org"
echo ""
echo "  After this, your API will be at:"
echo "     https://healthlens.duckdns.org"
echo "══════════════════════════════════════════════════════════"
